name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: apt-get 
      run: sudo apt-get update 

    - name: gcc
      run: |
        sudo apt install build-essential &&
        gcc --version 

    - name: build hello 
      run: |
        gcc -o hello.o hello.c  && 
        ./hello.o

    - name: fahrenheit
      run: | 
        gcc -o fahrenheit.o fahrenheit.c &&
        ./fahrenheit.o

    - name: exercise_1-3 
      run: | 
        gcc -o Exercise-1.3.o Exercise-1.3.c &&
        ./Exercise-1.3.o

    - name: exercise_1-4 
      run: | 
        gcc -o Exercise-1.4.o Exercise-1.4.c &&
        ./Exercise-1.4.o
