name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt-get 
      run: sudo apt-get update 
    - name: gcc
      run: sudo apt install build-essential
      run: gcc --version 
    - name: build hello 
      run: gcc -o hello.o hello.c 
      run: ./hello.o
